import random
import string

userData = []
container = []


firstName = input("Enter your first name: ")
lastName = input("Enter your last name: ")
emailAdd = input("Enter your email address: ")
#userData = {'firstname':firstName, 'lastname':lastName, 'email':emailAdd, 'password':userPwd}

def main():

  def randomString(stringLength = 5):

    letters = string.ascii_lowercase
    return " ".join(random.sample(letters,stringLength))
    
  userPwd = (firstName[0:2] + lastName[-2: ] + randomString(5))
  
  userData = {'firstname':firstName, 'lastname':lastName, 'email':emailAdd, 'password':userPwd}

  print("\n\nThis is your autogenerated password: ", userPwd)

